### ISSUE TITLE
No admites http://hola.com

### ISSUE THREAD

**Issue by lmagarin** [Javierfs94/Reentrega-Formulario-Completito-jQuery#10]

**Comment by Javierfs94** [comment]
He revisado mi regex: /^http[s]?:\/\/[w]{3}?\..+\.[a-z]{2,3}[[\/.+]*|\/]$/

Por más vueltas que he tratado de darle no consigo qutiar la parte del www. a ver si pudiera ayudarme a solucionarlo.

**Comment by lmagarin** [comment]
¿por qué tienes que poner las tres w?

**Comment by Javierfs94** [comment]
Claro me di cuenta que era una parte opcional, pero en la expresión al intentar hacerla, no me termina de salir y se empieza a liar mucho.

**Comment by lmagarin** [comment]
piensa en los puntos y poco más: tienen que llevan contenido entre medias que no sea espacio
aa.bb.cc
La primera parte admite 
http://
https://

**Comment by Javierfs94** [comment]
Oki, segui´re probando. Me atascaría tontamente, ya es hacerlo por coraje :)
